[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  
[[redirects]]
  from = "https://tkarap.netlify.com/*"
  to = "https://www.tkarap.com/:splat"
  status = 301
  force = true
