[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  
[[redirects]]
  from = "https://tkarap.netlify.com"
  to = "https://www.tkarap.com"
  status = 200
  force = true
